### ISSUE TITLE
404

### ISSUE THREAD

**Issue by GoSpud** [iwatkot/maps4fs#1]
I have tried different locations as well and sizes, and nothing seems to work.

And if you click on link it says not key.

           Fetched 67 weight files.                                                                      generate.py:167
           Fetching map data for coordinates: (48.291146294052, -117.94518134918403)...                   generate.py:94
           Map minimum coordinates (XxY): 421566.02060560987 x 5340808.599549268.                        generate.py:303
           Map maximum coordinates (XxY): 438193.9029467169 x 5357388.232686824.                         generate.py:304
           Map dimensions (HxW): 16579.633137555793 x 16627.882341107004.                                generate.py:308
           Map coefficients (HxW): 1.0119404991183956 x 1.0148853967960818.                              generate.py:312
           Map is in east of central meridian.                                                           generate.py:318
           Map is in north hemisphere.                                                                   generate.py:319
[19:36:07] Fetched 1 elements for tags: {'highway': ['motorway', 'trunk', 'primary']}.                   generate.py:437
           Texture C:\maps4fs\output\maps\map\data\asphalt01_weight.png saved.                           generate.py:452
[19:36:10] Fetched 129 elements for tags: {'building': True}.                                            generate.py:437
           Texture C:\maps4fs\output\maps\map\data\concrete01_weight.png saved.                          generate.py:452
[19:36:13] Fetched 176 elements for tags: {'highway': ['unclassified', 'residential', 'track']}.         generate.py:437
[19:36:14] Texture C:\maps4fs\output\maps\map\data\dirtDark01_weight.png saved.                          generate.py:452
[19:36:16] Fetched 53 elements for tags: {'landuse': 'farmland'}.                                        generate.py:437
[19:36:17] Texture C:\maps4fs\output\maps\map\data\forestGround01_weight.png saved.                      generate.py:452
[19:36:19] Fetched 23 elements for tags: {'natural': 'grassland'}.                                       generate.py:437
[19:36:20] Texture C:\maps4fs\output\maps\map\data\grass01_weight.png saved.                             generate.py:452
[19:36:23] Fetched 9 elements for tags: {'natural': ['wood', 'tree_row']}.                               generate.py:437
           Geometry type MultiPolygon not supported.                                                     generate.py:382
           Geometry type MultiPolygon not supported.                                                     generate.py:382
           Geometry type MultiPolygon not supported.                                                     generate.py:382
           Geometry type MultiPolygon not supported.                                                     generate.py:382
           Geometry type MultiPolygon not supported.                                                     generate.py:382
[19:36:24] Texture C:\maps4fs\output\maps\map\data\grassDirt01_weight.png saved.                         generate.py:452
[19:36:26] Fetched 8 elements for tags: {'highway': ['secondary', 'tertiary', 'road']}.                  generate.py:437
[19:36:27] Texture C:\maps4fs\output\maps\map\data\gravel01_weight.png saved.                            generate.py:452
[19:36:29] Fetched 13 elements for tags: {'natural': 'water', 'waterway': True}.                         generate.py:437
[19:36:30] Texture C:\maps4fs\output\maps\map\data\waterPuddle_weight.png saved.                         generate.py:452
           SRTM tile name N48E-117 from latitude band N48.                                               generate.py:499
           Trying to get response from                                                                   generate.py:477
           https://elevation-tiles-prod.s3.amazonaws.com/skadi/N48/N48E-117.hgt.gz...
           Response was failed with status code 404.                                                     generate.py:487
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\idaho\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\maps4fs\src\main.py", line 28, in start
    generate.Map(working_directory, (lat, lon), distance, dem_settings, logger)
  File "C:\maps4fs\src\generate.py", line 99, in __init__
    self.dem()
  File "C:\maps4fs\src\generate.py", line 523, in dem
    tile_path = self._srtm_tile()
                ^^^^^^^^^^^^^^^^^
  File "C:\maps4fs\src\generate.py", line 509, in _srtm_tile
    with gzip.open(compressed_file_path, "rb") as f_in:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\idaho\AppData\Local\Programs\Python\Python312\Lib\gzip.py", line 65, in open
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file

**Comment by iwatkot** [comment]
@GoSpud, hello!

Thanks for the report and for reaching out via Telegram. 
I have already answered you in private messages, here I will just duplicate my answer, saying that I will investigate the problem soon.

Sincerely

**Comment by iwatkot** [comment]
@GoSpud, hello again!

So, here's a summary.
1. I've fixed the issue with Error 404, the function to get the tile name was not aware that the second coordinate could be a negative value. :D
2. I also added some handling, so the script won't crash if the DEM map wasn't created for any reason and you'll just get a flat map.
3. When debugging your coordinates I also found a bug with incorrect rounding of negative coordinates.

Please check out the latest release and let me know if this works as expected now.

P.S. I've launched the Telegram bot again, you can try it.
Here's an example of your map:
![image](https://github.com/iwatkot/maps4fs/assets/118521851/34e909c1-e4e5-47bb-8b26-4d5216276751)
